services:

  # =========================
  # AUTH DATABASE
  # =========================
  postgres-auth:
    image: postgres:15
    container_name: aegis-postgres-auth
    environment:
      POSTGRES_DB: aegis_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aakash@123
    ports:
      - "5433:5432"

  # =========================
  # ORDER DATABASE
  # =========================
  postgres-order:
    image: postgres:15
    container_name: aegis-postgres-order
    environment:
      POSTGRES_DB: aegis_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aakash@123
    ports:
      - "5434:5432"

  # =========================
  # REDIS
  # =========================
  redis:
    image: redis:7
    container_name: aegis-redis
    ports:
      - "6379:6379"

  # =========================
  # AUTH SERVICE
  # =========================
  auth-service:
    build:
      context: ./aegis-auth-service
    container_name: aegis-auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth
      - redis

  # =========================
  # ORDER SERVICE
  # =========================
  order-service:
    build:
      context: ./aegis-order-service
    container_name: aegis-order-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-order

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: aegis-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: aegis-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
