services:

  # =========================
  # AUTH DATABASE
  # =========================
  postgres-auth:
    image: postgres:15
    container_name: aegis-postgres-auth
    environment:
      POSTGRES_DB: aegis_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aakash@123
    ports:
      - "5433:5432"

  # =========================
  # ORDER DATABASE
  # =========================
  postgres-order:
    image: postgres:15
    container_name: aegis-postgres-order
    environment:
      POSTGRES_DB: aegis_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aakash@123
    ports:
      - "5434:5432"

  # =========================
  # REDIS
  # =========================
  redis:
    image: redis:7
    container_name: aegis-redis
    ports:
      - "6379:6379"

  # =========================
  # AUTH SERVICE
  # =========================
  auth-service:
    build:
      context: ./aegis-auth-service
    container_name: aegis-auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth
      - redis

  # =========================
  # ORDER SERVICE
  # =========================
  order-service:
    build:
      context: ./aegis-order-service
    container_name: aegis-order-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-order

  notification-service:
    build:
      context: ./aegis-notification-service
    container_name: aegis-notification-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: aegis-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: aegis-kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data: